// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zekju.Infrastructure;

#nullable disable

namespace Zekju.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230325120703_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zekju.Domain.Model.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true)
                        .HasColumnType("integer")
                        .HasColumnName("flight_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("integer")
                        .HasColumnName("airline_id");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("arrival_time");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("departure_time");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.HasKey("Id");

                    b.HasIndex("DepartureTime");

                    b.HasIndex("RouteId");

                    b.ToTable("Flights", (string)null);
                });

            modelBuilder.Entity("Zekju.Domain.Model.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date")
                        .HasColumnName("departure_date");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_city_id");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_city_id");

                    b.HasKey("Id");

                    b.HasIndex("OriginCityId", "DestinationCityId");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("Zekju.Domain.Model.Subscription", b =>
                {
                    b.Property<int>("AgencyId")
                        .HasColumnType("integer")
                        .HasColumnName("agency_id");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_city_id");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_city_id");

                    b.HasKey("AgencyId", "OriginCityId", "DestinationCityId");

                    b.HasIndex("AgencyId", "OriginCityId", "DestinationCityId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Zekju.Domain.Model.Flight", b =>
                {
                    b.HasOne("Zekju.Domain.Model.Route", "Route")
                        .WithMany("Flights")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Zekju.Domain.Model.Route", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
